### ISSUE TITLE
Should this work with Jira Cloud?

### ISSUE THREAD

**Issue by steveharman** [RobertPlant/JIRA-Dark-Theme#12]
Hi,

I can't get this to work with our Jira Cloud instance (http://ourdomain.atlassian.net) - does it require Jira Server instead of Cloud?

Thanks,

Steve

**Comment by RobertPlant** [comment]
It should, its just a cloud hosted version, There may be some small inconsistencies but I do not have access to an instance of Jira Cloud to test against so I cannot say for sure that it works.
