### ISSUE TITLE
Top menus are styled wrong

### ISSUE THREAD

**Issue by MarcinOrlowski** [RobertPlant/JIRA-Dark-Theme#2]
Top menus (both links and menu content) is rendered unreadable when this theme is applied. See the screenshots (I am using Tampermonkey, and recent version of  theme (installed today via userscripts.org).

![top-menus](https://cloud.githubusercontent.com/assets/8041294/19360533/4423caf2-917f-11e6-9351-3c796df47805.png)

The content of the menu is not readable:

![menu-no-focus](https://cloud.githubusercontent.com/assets/8041294/19360639/9e30598e-917f-11e6-997b-b7c59a8be742.png)

unless you move mouse over it. 

![menu-focus](https://cloud.githubusercontent.com/assets/8041294/19360641/a06a829c-917f-11e6-889e-e00f9cf8dd96.png)

**Comment by RobertPlant** [comment]
Cant replicate this issue on https://jira.atlassian.com/secure/Dashboard.jspa
