### ISSUE TITLE
Time sheet gadget (on dashboard) Header bar CSS

### ISSUE THREAD

**Issue by hasteur** [RobertPlant/JIRA-Dark-Theme#4]
Compiled CSS selector div#slider-wrapper
Change background-color value from #e0f0ff to #333333.

**Comment by hasteur** [comment]
Before: 
![image](https://user-images.githubusercontent.com/188451/26881072-f9a23c9c-4b5b-11e7-9e9c-a3b60aa2e9c6.png)

After:
![image](https://user-images.githubusercontent.com/188451/26881091-0978edaa-4b5c-11e7-8948-da4ce9c8138d.png)

**Comment by RobertPlant** [comment]
Fixed in commit 2b29f5935adb51060f9f1bdb47de2aa99970be86
